services:
  - type: web
    name: TimkossikBot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
